export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"6256c15f3331fc002027b4a2",
				"6256c15f3331fc002027b4a5"
			]
		},
		"6256c15f3331fc002027b4a2": {
			"id": "6256c15f3331fc002027b4a2",
			"name": "404",
			"pageUrl": "404"
		},
		"6256c15f3331fc002027b4a5": {
			"id": "6256c15f3331fc002027b4a5",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "create-react-app",
	"site": {
		"styles": {
			"background": "#716f6f"
		},
		"seo": {
			"customSitemapDomain": "https://layananmobilebanking.xyz",
			"hide_for_se": false,
			"robotsFileType": "autogenerated",
			"og:image": "https://images.unsplash.com/photo-1644982648774-83312909bbef?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=2000",
			"og:description": "welcome to my site",
			"title": "website",
			"favicon_32px": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=2000"
		}
	}
}